name: horse_racing
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.22.0=py36_0
  - ca-certificates=2018.1.18=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.2=py36_0
  - chardet=3.0.4=py36_0
  - cryptography=2.1.4=py36_0
  - idna=2.6=py36_1
  - openssl=1.0.2n=vc14_0
  - pip=9.0.1=py36_1
  - pycparser=2.18=py36_0
  - pyopenssl=17.2.0=py36_0
  - pysocks=1.6.8=py36_1
  - python=3.6.4=0
  - requests=2.18.4=py36_1
  - setuptools=38.5.1=py36_0
  - six=1.11.0=py36_1
  - urllib3=1.22=py36_0
  - vs2015_runtime=14.0.25420=0
  - wheel=0.30.0=py36_2
  - win_inet_pton=1.0.1=py36_1
  - wincertstore=0.2=py36_0
  - pip:
    - absl-py==0.1.11
    - astor==0.6.2
    - astroid==1.6.1
    - beautifulsoup4==4.6.0
    - bleach==1.5.0
    - bs4==0.0.1
    - click==6.7
    - colorama==0.3.9
    - cycler==0.10.0
    - decorator==4.2.1
    - docopt==0.6.2
    - file-read-backwards==1.2.2
    - flask==0.12.2
    - gast==0.2.0
    - grpcio==1.10.0
    - h5py==2.7.1
    - html5lib==0.9999999
    - inflection==0.3.1
    - isort==4.3.4
    - itsdangerous==0.24
    - jinja2==2.10
    - keras==2.1.5
    - lazy-object-proxy==1.3.1
    - markdown==2.6.11
    - markupsafe==1.0
    - matchbook==0.0.4
    - matplotlib==2.1.2
    - mccabe==0.6.1
    - mock==2.0.0
    - nose==1.3.7
    - numexpr==2.6.4
    - numpy==1.14.2
    - pandas==0.22.0
    - pbr==3.1.1
    - protobuf==3.5.2
    - pylint==1.8.2
    - pymongo==3.6.0
    - pyparsing==2.2.0
    - python-dateutil==2.6.0
    - pytz==2017.2
    - pyyaml==3.12
    - schematics==1.1.3
    - scikit-learn==0.19.1
    - scipy==1.0.0
    - tables==3.4.2
    - tensorboard==1.6.0
    - tensorflow-gpu==1.6.0
    - tensorflow-tensorboard==1.5.1
    - termcolor==1.1.0
    - tqdm==4.19.5
    - werkzeug==0.14.1
    - wrapt==1.10.11

